### ISSUE TITLE
Link is no longer valid

### ISSUE THREAD

**Issue by christ66** [sonatype/sonatype-ci-for-jenkins#1]
Looking at the code: https://github.com/sonatype/sonatype-ci-for-jenkins/blob/8716ce1b502a832051192df3b1dfb00cc71070ff/src/main/resources-filtered/org/sonatype/ci/jenkins/SonatypeSites.json#L3

is no longer a valid url and redirects to: https://sonatype-download.global.ssl.fastly.net/clm/ci/insight-ci-2.3.3-update-center.json. 

In newer versions of Jenkins core this plugin throws the following exception:

```
java.io.IOException: Could not find JSON in http://links.sonatype.com/products/insight/ci/jenkins-plugins?id=insight-ci&version=1.625.1
at hudson.model.DownloadService.loadJSON(DownloadService.java:170)
at hudson.model.UpdateSite.updateDirectlyNow(UpdateSite.java:173)
at hudson.PluginManager.doCheckUpdatesServer(PluginManager.java:894)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by aheritier** [comment]
@brianf could you help us please to have this fixed? Don't hesitate to reach me if required. It seems that more and more users are impacted by this (and from my POV Jenkins doesn't handle such error nicely, it should better skip the failing UC instead of the `Oops!` page. WDYT @danielbeck @christ66 ?)

**Comment by brianf** [comment]
@aheritier is the issue that Jenkins won't follow a redirect here?

links.sonatype.com is where we put all links that we bake into the products and they are all redirects to the proper place. In other words, it isn't a case of this being no longer valid, it was always a redirect by design.

**Comment by brianf** [comment]
@aheritier my bad, I didn't realize this was the old plugin, I was thinking it was the new pipeline stuff. This old version has been deprecated years ago and should have been pulled down all together. If it's still out there somewhere, we should remove it.

**Comment by aheritier** [comment]
Hi @brianf 

  Sorry for the delay. I will informing people reporting me this issue that it is deprecated and I'll provide them the link to https://wiki.jenkins-ci.org/display/JENKINS/Sonatype+CLM+%28formerly+Insight+for+CI%29

Thanks a lot
